# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: å®‰çŸ¥é±¼
subtitle: 'ç”Ÿæ´»æ˜æœ— ä¸‡ç‰©å¯çˆ±'
description: 'ç”Ÿæ´»æ˜æœ—,ä¸‡ç‰©å¯çˆ±.'
keywords: å®‰çŸ¥é±¼,å®‰çŸ¥é±¼çš„åšå®¢,åšå®¢,å®‰çŸ¥é±¼åšå®¢,é™ˆå¿—ä¼Ÿ,Blog,anzhiyu,å®‰çŸ¥é±¼`Blog,hexo,ANZHIYU, HEXO anzhiyu,Blog,anzhiyu`Blog,ğŸ’–,å®‰,å®‰çŸ¥,å®‰çŸ¥é±¼,Inå®‰çŸ¥é±¼,Goå®‰çŸ¥é±¼,anzhiy
author: å®‰çŸ¥é±¼
language: zh-CN
timezone:
email: anzhiy-c@qq.com

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://anzhiy.cn
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository:
      # github: git@github.com:anzhiyu-c/anzhiyu-c.github.io.git  #ç”¨æˆ·å@æœåŠ¡å™¨Ip:gitä»“åº“ä½ç½®
      github: https://anzhiyu-c:xxx@github.com/anzhiyu-c/anzhiyu-c.github.io.git
    branch: master
  - type: baidu_url_submitter # è¿™æ˜¯æ–°åŠ çš„ç™¾åº¦ä¸»åŠ¨æ¨é€

# æ–‡ç« é“¾æ¥è½¬æ•°å­—æˆ–å­—æ¯ï¼šhttps://github.com/rozbo/hexo-abbrlink
abbrlink:
	alg: crc16   #ç®—æ³•ï¼š crc16(default) and crc32
	rep: hex     #è¿›åˆ¶ï¼š dec(default) and hex: dec #è¾“å‡ºè¿›åˆ¶ï¼šåè¿›åˆ¶å’Œåå…­è¿›åˆ¶ï¼Œé»˜è®¤ä¸º10è¿›åˆ¶ã€‚ä¸¨decä¸ºåè¿›åˆ¶ï¼Œhexä¸ºåå…­è¿›åˆ¶

# æœ¬åœ°æœç´¢ï¼šhttps://github.com/wzpan/hexo-generator-search
search:
  path: search.xml
  field: all
  content: true

# Live2D
## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true #å¼€å…³æ’ä»¶ç‰ˆçœ‹æ¿å¨˜
  scriptFrom: local # é»˜è®¤
  # scriptFrom: https://cdn.cbd.int/live2d-widget@3.x/lib/L2Dwidget.min.js # ä½ çš„è‡ªå®šä¹‰ url
  tagMode: false # æ ‡ç­¾æ¨¡å¼, æ˜¯å¦ä»…æ›¿æ¢ live2d tagæ ‡ç­¾è€Œéæ’å…¥åˆ°æ‰€æœ‰é¡µé¢ä¸­
  debug: false # è°ƒè¯•, æ˜¯å¦åœ¨æ§åˆ¶å°è¾“å‡ºæ—¥å¿—
  model:
    use: live2d-widget-model-koharu # npm-module package name
    # use: https://unpkg.com/live2d-widget-model-koharu@1.0.5/assets/koharu.model.json # ä½ çš„è‡ªå®šä¹‰ url
  display:
    position: left #æ§åˆ¶çœ‹æ¿å¨˜ä½ç½®
    width: 150 #æ§åˆ¶çœ‹æ¿å¨˜å¤§å°
    height: 300 #æ§åˆ¶çœ‹æ¿å¨˜å¤§å°
  mobile:
    show: false # æ‰‹æœºä¸­æ˜¯å¦å±•ç¤º

# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml
  rel: false
  tags: true
  categories: true

# https://github.com/coneycode/hexo-generator-baidu-sitemap
baidusitemap:
    path: baidusitemap.xml

# https://github.com/hexojs/hexo-generator-feed
#Feed Atom
feed:
    type: atom
    path: atom.xml
    limit: 20
rss: /atom.xml

# Extensions
plugins:
    - hexo-generator-feed
    - hexo-generator-baidu-sitemap
    - hexo-generator-sitemap

# è¿½ç•ªæ’ä»¶
# https://github.com/HCLonely/hexo-bilibili-bangumi
bangumi: # è¿½ç•ªè®¾ç½®
  enable: true
  path:
  vmid: 372204786
  title: 'è¿½ç•ªåˆ—è¡¨'
  quote: 'ç”Ÿå‘½ä¸æ¯ï¼Œè¿½ç•ªä¸æ­¢ï¼'
  show: 1
  lazyload: false
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value
cinema: # è¿½å‰§è®¾ç½®
  enable: false
  path:
  vmid: 372204786
  title: 'è¿½å‰§åˆ—è¡¨'
  quote: 'ç”Ÿå‘½ä¸æ¯ï¼Œè¿½å‰§ä¸æ­¢ï¼'
  show: 1
  lazyload: true
  loading:
  metaColor:
  color:
  webp:
  progress:
  extra_options:
    key: value

# ç™¾åº¦ä¸»åŠ¨æ¨é€
# https://github.com/huiwang/hexo-baidu-url-submit
baidu_url_submit:
  count: 1        # æäº¤æœ€æ–°çš„å¤šå°‘ä¸ªé“¾æ¥
  host: blog.anzhiy.cn  # åœ¨ç™¾åº¦ç«™é•¿å¹³å°ä¸­æ·»åŠ çš„åŸŸå
  token: Rgem9kAECSLflQq6   # ç§˜é’¥
  path: baidu_urls.txt   # æ–‡æœ¬æ–‡æ¡£çš„åœ°å€ï¼Œ æ–°é“¾æ¥ä¼šä¿å­˜åœ¨æ­¤æ–‡æœ¬æ–‡æ¡£é‡Œ

# APlayer
# https://github.com/MoePlayer/hexo-tag-aplayer/blob/master/docs/README-zh_cn.md
aplayer:
  meting: true
  asset_inject: false

# Artitalk
# see https://artitalk.js.org/
# https://github.com/jerryc127/butterfly-plugins/tree/main/hexo-butterfly-artitalk
artitalk:
  enable: true
  appId: xxxxxx
  appKey: xxxxxxxx
  path: artitalk
  js: https://cdn.cbd.int/artitalk
  option:
    shuoPla: å†™ä¸‹ä»Šå¤©çš„å¿«ä¹å­~
    avatarPla: https://cdn.cbd.int/anzhiyu-blog@latest/img/post/common/avatar.png
    bgImg: https://cdn.cbd.int/anzhiyu-blog@latest/img/post/common/comment_bg.png
    atEmoji: {
        "é…·å®‰-1": "https://7.dusays.com/2021/01/15/d79edde04bd03.png",
        "é…·å®‰-10": "https://7.dusays.com/2021/01/15/e84b0ea48383a.png",
        "é…·å®‰-11": "https://7.dusays.com/2021/01/15/29be1c9d7042d.png",
        "é…·å®‰-12": "https://7.dusays.com/2021/01/15/bfba60ecb6cc6.png",
        "é…·å®‰-13": "https://7.dusays.com/2021/01/15/6019afc31c8d2.png",
        "é…·å®‰-14": "https://7.dusays.com/2021/01/15/3fb064da5dac2.png",
        "é…·å®‰-15": "https://7.dusays.com/2021/01/15/f127ba6ee794a.png",
        "é…·å®‰-16": "https://7.dusays.com/2021/01/15/f1a49c89ec203.png",
        "é…·å®‰-17": "https://7.dusays.com/2021/01/15/03d8aa90d5ffa.png",
        "é…·å®‰-18": "https://7.dusays.com/2021/01/15/238a7c446f1da.png",
        "é…·å®‰-2": "https://7.dusays.com/2021/01/15/725e848a16e1d.png",
        "é…·å®‰-3": "https://7.dusays.com/2021/01/15/156aacb8fde41.png",
        "é…·å®‰-4": "https://7.dusays.com/2021/01/15/49257728eeac3.png",
        "é…·å®‰-5": "https://7.dusays.com/2021/01/15/ef52bbdb8dba2.png",
        "é…·å®‰-6": "https://7.dusays.com/2021/01/15/5e1f58a22eb1b.png",
        "é…·å®‰-7": "https://7.dusays.com/2021/01/15/ae09426ffc052.png",
        "é…·å®‰-8": "https://7.dusays.com/2021/01/15/cc0bd57e14172.png",
        "é…·å®‰-9": "https://7.dusays.com/2021/01/15/98b032b2a71a9.png",
        "é…·å®‰-aixin": "https://7.dusays.com/2021/01/15/e39a8e16b7f6d.png",
        "é…·å®‰-aoman": "https://7.dusays.com/2021/01/15/fdcffa4a8ae4c.png",
        "é…·å®‰-baiyan": "https://7.dusays.com/2021/01/15/98699918092c8.png",
        "é…·å®‰-baoquan": "https://7.dusays.com/2021/01/15/bf297cbf79577.png",
        "é…·å®‰-bishi": "https://7.dusays.com/2021/01/15/59be811ed5b68.png",
        "é…·å®‰-caidao": "https://7.dusays.com/2021/01/15/59baa938beee7.png",
        "é…·å®‰-chigua": "https://7.dusays.com/2021/01/15/8b1afe90b91b8.png",
        "é…·å®‰-ciya": "https://7.dusays.com/2021/01/15/b2c520003cfe2.png",
        "é…·å®‰-coshuaji": "https://7.dusays.com/2021/01/15/f49a7ee4bac5b.png",
        "é…·å®‰-diaoxie": "https://7.dusays.com/2021/01/15/bb0b8e68db729.png",
        "é…·å®‰-doge": "https://7.dusays.com/2021/01/15/7b15f7732d333.png",
        "é…·å®‰-dogehechi": "https://7.dusays.com/2021/01/15/b44cb17d1be10.png",
        "é…·å®‰-dogexiaoku": "https://7.dusays.com/2021/01/15/b8cc577aeab99.png",
        "é…·å®‰-dogeyuanliangta": "https://7.dusays.com/2021/01/15/3de6674a8e701.png",
        "é…·å®‰-doujiyanhuaji": "https://7.dusays.com/2021/01/15/82492e225e877.png",
        "é…·å®‰-erha": "https://7.dusays.com/2021/01/15/6417d51eab768.png",
        "é…·å®‰-erhading": "https://7.dusays.com/2021/01/15/893603585a2d5.png",
        "é…·å®‰-fadai": "https://7.dusays.com/2021/01/15/e91650e7074c2.png",
        "é…·å®‰-fanu": "https://7.dusays.com/2021/01/15/7c8a82e5ae7a1.png",
        "é…·å®‰-hahaha": "https://7.dusays.com/2021/01/15/60330b48c5002.png",
        "é…·å®‰-haixiu": "https://7.dusays.com/2021/01/15/67057f65ef6a9.png",
        "é…·å®‰-han": "https://7.dusays.com/2021/01/15/bd91e01f60814.png",
        "é…·å®‰-hehe": "https://7.dusays.com/2021/01/15/17fbf7df839d6.png",
        "é…·å®‰-heiha": "https://7.dusays.com/2021/01/15/5f8b8d3350d53.png",
        "é…·å®‰-heixian": "https://7.dusays.com/2021/01/15/7a6f5ac8df889.png",
        "é…·å®‰-hejiu": "https://7.dusays.com/2021/01/15/f456859d769a5.png",
        "é…·å®‰-hongyaowan": "https://7.dusays.com/2021/01/15/205c0e553f962.png",
        "é…·å®‰-huaixiao": "https://7.dusays.com/2021/01/15/aa0280dd17f73.png",
        "é…·å®‰-huaji": "https://7.dusays.com/2021/01/15/bc5d47be7dd61.png",
        "é…·å®‰-huanhu": "https://7.dusays.com/2021/01/15/e3645bd074e47.png",
        "é…·å®‰-huoba": "https://7.dusays.com/2021/01/15/52bccfd07cd42.png",
        "é…·å®‰-jingya": "https://7.dusays.com/2021/01/15/fa28851b21757.png",
        "é…·å®‰-jizhi": "https://7.dusays.com/2021/01/15/8fb3db20e2970.png",
        "é…·å®‰-keai": "https://7.dusays.com/2021/01/15/fad3ad127dc91.png",
        "é…·å®‰-kelian": "https://7.dusays.com/2021/01/15/63d75bb5d6deb.png",
        "é…·å®‰-koubi": "https://7.dusays.com/2021/01/15/c22c18faf18fd.png",
        "é…·å®‰-ku": "https://7.dusays.com/2021/01/15/fced019d8cd36.png",
        "é…·å®‰-kuan": "https://7.dusays.com/2021/01/15/196e9683bb4c2.png",
        "é…·å®‰-kuanlvmao": "https://7.dusays.com/2021/01/15/3bd36495075b6.png",
        "é…·å®‰-liuhanhuaji": "https://7.dusays.com/2021/01/15/0677bec17b611.png",
        "é…·å®‰-liulei": "https://7.dusays.com/2021/01/15/f06eac9acc4db.png",
        "é…·å®‰-lvmao": "https://7.dusays.com/2021/01/15/3ad6bcbc4661f.png",
        "é…·å®‰-lvyaowan": "https://7.dusays.com/2021/01/15/eaae5763e0650.png",
        "é…·å®‰-meigui": "https://7.dusays.com/2021/01/15/7d0791eb5bf30.png",
        "é…·å®‰-miaomiao": "https://7.dusays.com/2021/01/15/d2ea812f4dfb5.png",
        "é…·å®‰-mojinghuaji": "https://7.dusays.com/2021/01/15/91338ab3e04b9.png",
        "é…·å®‰-naikezui": "https://7.dusays.com/2021/01/15/7c547fda1e34e.png",
        "é…·å®‰-nanguo": "https://7.dusays.com/2021/01/15/4f065524c5233.png",
        "é…·å®‰-nb": "https://7.dusays.com/2021/01/15/2aca7bdb0ebe2.png",
        "é…·å®‰-ok": "https://7.dusays.com/2021/01/15/a53470afa1c1f.png",
        "é…·å®‰-pen": "https://7.dusays.com/2021/01/15/39077063f798d.png",
        "é…·å®‰-penxue": "https://7.dusays.com/2021/01/15/f793f26b74ddb.png",
        "é…·å®‰-piezui": "https://7.dusays.com/2021/01/15/3fe36dc5ad166.png",
        "é…·å®‰-pu": "https://7.dusays.com/2021/01/15/557d698e30855.png",
        "é…·å®‰-pyjiaoyi": "https://7.dusays.com/2021/01/15/cafc37786127e.png",
        "é…·å®‰-qiang": "https://7.dusays.com/2021/01/15/ee5220d999068.png",
        "é…·å®‰-qinqin": "https://7.dusays.com/2021/01/15/3d8a0587f57f0.png",
        "é…·å®‰-qqdoge": "https://7.dusays.com/2021/01/15/3b782640f81ef.png",
        "é…·å®‰-ruo": "https://7.dusays.com/2021/01/15/1f9103176b58a.png",
        "é…·å®‰-se": "https://7.dusays.com/2021/01/15/e46710cff9b8c.png",
        "é…·å®‰-shounuehuaji": "https://7.dusays.com/2021/01/15/1c131772d1bb2.png",
        "é…·å®‰-shui": "https://7.dusays.com/2021/01/15/27fecb3f84bc7.png",
        "é…·å®‰-tuosai": "https://7.dusays.com/2021/01/15/d211229511504.png",
        "é…·å®‰-tushe": "https://7.dusays.com/2021/01/15/983c8ebd87cf2.png",
        "é…·å®‰-weiqu": "https://7.dusays.com/2021/01/15/ee0a562c20067.png",
        "é…·å®‰-weiweiyixiao": "https://7.dusays.com/2021/01/15/d281ccdecda1a.png",
        "é…·å®‰-weixiao": "https://7.dusays.com/2021/01/15/9ef8b76db9b9c.png",
        "é…·å®‰-wozuimei": "https://7.dusays.com/2021/01/15/996e570245530.png",
        "é…·å®‰-wulian": "https://7.dusays.com/2021/01/15/7e872f685ca1b.png",
        "é…·å®‰-wunai": "https://7.dusays.com/2021/01/15/98741ccc53a16.png",
        "é…·å®‰-wuyu": "https://7.dusays.com/2021/01/15/def9868ab4f79.png",
        "é…·å®‰-wuzuixiao": "https://7.dusays.com/2021/01/15/46bbf77822f18.png",
        "é…·å®‰-xiaoku": "https://7.dusays.com/2021/01/15/fe27d3c2dbbf8.png",
        "é…·å®‰-xiaoyan": "https://7.dusays.com/2021/01/15/64d03bece8262.png",
        "é…·å®‰-xinsui": "https://7.dusays.com/2021/01/15/d94af60c9fb37.png",
        "é…·å®‰-ye": "https://7.dusays.com/2021/01/15/7f9cf72ba2ecd.png",
        "é…·å®‰-yinxian": "https://7.dusays.com/2021/01/15/c32feba1e8817.png",
        "é…·å®‰-yiwen": "https://7.dusays.com/2021/01/15/bc7a5a28808fb.png",
        "é…·å®‰-zaijian": "https://7.dusays.com/2021/01/15/b25ccbf1814ae.png",
        "é…·å®‰-zhoumei": "https://7.dusays.com/2021/01/15/6bd6239753b7a.png"
      }
  front_matter:
    title: é—²è¨€ç¢è¯­
    comments: false
    date: 2021-03-30 15:57:50
    copyright_author: å®‰çŸ¥é±¼
    cover: https://cdn.cbd.int/anzhiyu-blog@latest/img/post/common/anzhiy.cn.jpg

# hpptalk:
#   enable: true
#   domain: chen.2268025923.workers.dev
#   path: hpptalk
#   limit: 8
#   start: 0
#   js: https://cdn.jsdelivr.net/gh/HexoPlusPlus/HexoPlusPlus@latest/talk_user.js
#   css: https://cdn.jsdelivr.net/gh/anzhiyu-c/cdn/qiqi/css/hpptalk.css
#   option:
#   front_matter:
#     title: é—²è¨€ç¢è¯­
#     date: 2021-03-30 15:57:50
#     comments: false
